# Generated by Django 2.1.5 on 2019-03-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=400, verbose_name='Motivo de Inversion')),
                ('interes', models.FloatField(blank=True, default=None, null=True, verbose_name='Tasa de intres')),
                ('monto', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha agregada')),
            ],
        ),
    ]
